name: CI/CD with Docker

on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code from GitHub repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Docker Buildx (for multi-platform support)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Log in to DockerHub (if using DockerHub for image storage)
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Create .env file from GitHub Secrets
    - name: Create .env file
      run: echo "${{ secrets.ENV }}" > ./src/.env

    # 5. Build and push Docker image
    - name: Build & push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64
        tags: ${{ secrets.DOCKER_REPO }}:latest
        
    # 6. SSH to EC2 and deploy Docker container
    - name: SSH to EC2 & deploy Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        envs: GITHUB_SHA
        script: |
          sudo docker ps -qa | xargs -r sudo docker rm -f
          sudo docker pull ${{ secrets.DOCKER_REPO }}:latest
          sudo docker run -d -p 8000:8000 ${{ secrets.DOCKER_REPO }}:latest
          sudo docker image prune -f
